version: '3.5'

services:
  x-nginx:
    container_name: x-nginx
    build: ./docker/nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx/mecash.conf:/etc/nginx/conf.d/mecash.conf
      - nginx_logs:/var/log/nginx/
      - mecash:/var/www/mecash
#    command: bash -c "chmod +x /wait-for-it.sh && /wait-for-it.sh x-mecash:9000 && nginx -g 'daemon off;'"
    links:
      - x-mecash:mecash.loc
    networks:
      default:
        ipv4_address: 172.18.0.5

  x-mecash:
    container_name: x-mecash
    image: mecash:latest
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST_IP} remote_port=${MECASH_XDEBUG_PORT}"
      PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
    ports:
      - '3333:3333'
    volumes:
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www3.conf
      - mecash:/var/www/mecash
      - mecash_logs:/var/www/logs#
    networks:
      default:
        ipv4_address: 172.18.0.6

  x-memcached:
    container_name: x-memcached
    image: memcached:alpine
    ports:
      - 11211:11211
    networks:
      default:
        ipv4_address: 172.18.0.7

  x-redis:
    container_name: x-redis
    image: grokzen/redis-cluster
    ports:
      - 6379:6379
      - 6380:6380
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
    networks:
      default:
        ipv4_address: 172.18.0.8

  x-rabbitmq:
    image: rabbitmq:3-management
    container_name: x-rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 15672:15672
    networks:
      default:
        ipv4_address: 172.18.0.9

  x-mongo:
    image: mongo
    container_name: x-mongo
    volumes:
      - mongodb:/var/lib/mongo
    ports:
      - 27017:27017
    networks:
      default:
        ipv4_address: 172.18.0.11

volumes:
  mecash:
  mecash_logs:
  nginx_logs:
  profiler_mecash:
  rabbitmq:
  mongodb:

networks:
  default:
    external:
      name: x-network

